server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/Virtusa
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret=MySuperSecureJwtSecretKeyForLeaveManagementSystem2026
jwt.expiration=86400000
